[package]
name = "merkle"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.11.0-rc.3"
tempfile = "3.24.0"
rand = "0.10.0-rc.6"
flate2 = { version = "^1.1.5", features = ["zlib-rs"], default-features = false }