[package]
name = "FreeSync"
version = "0.1.0"
edition = "2024"

[dependencies]
merkle = { path = "src/merkle" }

[workspace]
members = [
    "src/merkle",
    "src/server",
    "src/client", "src/logger",
]
